### ISSUE TITLE
All visuals have disappeared? 

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_dash#31] opened 2016-10-12 07:34 UTC
I only see the map and government stats now. All other categories are empty. Did a ctrl F5 and that didn't do anything. I'm using Chrome. 

![image](https://cloud.githubusercontent.com/assets/14996905/19301239/b6927588-905e-11e6-8132-2e81524df207.png)
![image](https://cloud.githubusercontent.com/assets/14996905/19301248/c4affdca-905e-11e6-8de3-bc1dd3f3f833.png)
![image](https://cloud.githubusercontent.com/assets/14996905/19301263/dc4b29c8-905e-11e6-8588-e346d4c41e0b.png)

**Comment by DragonVirus** [comment] 2016-10-12 08:23
@prustar 
is it on the pp site ? Currently, i will only work on production site. cuz @acorbi limited the production ckan request only from production sites. 
https://opendevelopmentmyanmar.net/dashboard/myanmar-data

i need to implement with data request from pp ckan site on pp sites but the problem is we don't have dataset uploaded on pp ckan site. I will implement it with config since i will start to work on modularizing the dashboard.

**Comment by acorbi** [comment] 2016-10-12 12:18
@DragonVirus yes, I'll add this to the agenda on our call around modularizing the code of the dashboard plugin.

@prustar im discussing with @DragonVirus how to modularize the wp-odm_dash plugin next thursday (see TWPM calendar) so it can be re-use across the platform. It is going to be just on the tech level but you are welcome to participate if you want.

**Comment by acorbi** [comment] 2016-10-20 12:09
this should be now fixed after enabling CORS on PROD for requests from PP. closing

**Closed as completed by acorbi** 2016-10-20 12:09 UTC
